CREATE TABLE livro(
id_livro INT PRIMARY KEY AUTO_INCREMENT, 
sinopse TEXT, 
autor VARCHAR(128) NOT NULL, 
editora VARCHAR(128) NOT NULL, 
categoria VARCHAR(128) NOT NULL, 
ano_publicação DATE NOT NULL
);